"""JSONL + path handling shared by every CLI.

Two jobs, both about not trusting the input file:

**Parsing.** A manifest is data, often generated by some other pipeline. A bad line
should name itself (``manifest.jsonl:4217``) instead of surfacing as a bare
``JSONDecodeError`` a thousand clips into a GPU run.

**Path resolution.** ``wav_path`` is an arbitrary string from that file and gets
handed to the audio decoder. :func:`resolve_audio_path` requires it to name a real
regular file and, when an ``audio_root`` is given, to stay inside that root — so a
manifest carrying a parent-directory traversal or a symlink pointing out of the corpus is
rejected up front rather than read.

Writers are append-and-flush (so a killed run keeps every clip it finished) or
atomic via a temp file + ``os.replace`` (so a killed run never leaves a half-written
file where a complete one used to be).
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
import zlib
from pathlib import Path
from typing import Any, Iterable, Iterator


class ManifestError(ValueError):
    """A manifest line is unusable; the message carries file:line."""


def read_jsonl(path: str | os.PathLike, required: Iterable[str] = ()) -> Iterator[dict]:
    """Yield one dict per non-blank line, reporting file:line on any problem."""
    required = tuple(required)
    with open(path, "r", encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as e:
                raise ManifestError(f"{path}:{lineno}: invalid JSON ({e.msg})") from None
            if not isinstance(obj, dict):
                raise ManifestError(f"{path}:{lineno}: expected a JSON object")
            missing = [k for k in required if not obj.get(k)]
            if missing:
                raise ManifestError(f"{path}:{lineno}: missing field(s) {missing}")
            yield obj


def load_jsonl(path: str | os.PathLike, required: Iterable[str] = (),
               limit: int = 0) -> list[dict]:
    rows = []
    for row in read_jsonl(path, required):
        rows.append(row)
        if limit and len(rows) >= limit:
            break
    return rows


def index_by_id(path: str | os.PathLike, warn_dupes: bool = True) -> dict[str, dict]:
    """Load a sidecar jsonl into {id: row}. Later rows win; duplicates are reported
    rather than silently collapsed (a duplicated id means one clip's result is lost)."""
    out: dict[str, dict] = {}
    dupes = 0
    for row in read_jsonl(path, required=("id",)):
        if row["id"] in out:
            dupes += 1
        out[row["id"]] = row
    if dupes and warn_dupes:
        print(f"[warn] {path}: {dupes} duplicate id(s); kept the last occurrence",
              file=sys.stderr)
    return out


def dumps(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False)


class JsonlWriter:
    """Append-mode writer that flushes every record — a killed run keeps its progress.

    ``path`` may be empty, in which case the writer is a no-op sink; that keeps the
    "write to stdout only" case out of the caller's control flow.
    """

    def __init__(self, path: str | os.PathLike | None, append: bool = False):
        self.path = str(path) if path else ""
        self._mode = "a" if append else "w"
        self._f = None

    def __enter__(self) -> "JsonlWriter":
        if self.path:
            parent = os.path.dirname(os.path.abspath(self.path))
            os.makedirs(parent, exist_ok=True)
            self._f = open(self.path, self._mode, encoding="utf-8")
        return self

    def write(self, obj: Any) -> None:
        if self._f is not None:
            self._f.write(dumps(obj) + "\n")
            self._f.flush()

    def __exit__(self, *exc) -> None:
        if self._f is not None:
            self._f.close()
            self._f = None


def write_jsonl_atomic(path: str | os.PathLike, rows: Iterable[Any]) -> int:
    """Write via a temp file in the same directory + ``os.replace``.

    Used where the destination is also the source (the caption merge rewrites the
    annotation file in place): a crash mid-write must not destroy the input.
    """
    path = os.fspath(path)
    parent = os.path.dirname(os.path.abspath(path)) or "."
    os.makedirs(parent, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=parent, prefix=".continuo-", suffix=".jsonl.tmp")
    n = 0
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            for row in rows:
                f.write(dumps(row) + "\n")
                n += 1
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise
    return n


def done_ids(path: str | os.PathLike) -> set[str]:
    """Ids already present in an output file, for --resume. Tolerates a truncated
    final line (the usual shape of a killed run)."""
    ids: set[str] = set()
    if not path or not os.path.exists(path):
        return ids
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue                      # partial last line from a hard kill
            if isinstance(obj, dict) and obj.get("id"):
                ids.add(obj["id"])
    return ids


# --------------------------------------------------------------------------- paths
def resolve_audio_path(raw: Any, audio_root: str | os.PathLike | None = None) -> Path:
    """Validate a manifest ``wav_path`` and return an absolute, existing file path.

    Relative paths resolve against ``audio_root`` when given, else the cwd. With an
    ``audio_root``, the fully-resolved path (symlinks followed) must stay inside it.
    """
    if not isinstance(raw, str) or not raw.strip():
        raise ManifestError(f"wav_path must be a non-empty string, got {raw!r}")
    if "\x00" in raw:
        raise ManifestError("wav_path contains a NUL byte")

    root = Path(audio_root).expanduser().resolve() if audio_root else None
    p = Path(raw).expanduser()
    if not p.is_absolute():
        p = (root or Path.cwd()) / p
    p = p.resolve()

    if root is not None and root not in p.parents and p != root:
        raise ManifestError(f"{raw!r} resolves outside --audio-root {root}")
    if not p.exists():
        raise ManifestError(f"audio file not found: {p}")
    if not p.is_file():
        raise ManifestError(f"not a regular file: {p}")
    return p


def safe_name(value: Any, kind: str = "id") -> str:
    """Validate an id that is about to be used as a filename.

    Ids arrive from corpus metadata — for the long-audio path, a JSON sidecar packed
    inside a tar — and get joined onto an output directory. One holding a separator, a
    parent reference or a leading slash would put files anywhere on the filesystem,
    which is the same trust boundary :func:`resolve_audio_path` guards on the way in.

    Rejecting beats sanitising here: a rewritten id no longer joins back to the corpus
    it came from, so a quietly renamed clip is a silently corrupted dataset.
    """
    if not isinstance(value, str) or not value.strip():
        raise ManifestError(f"{kind} must be a non-empty string, got {value!r}")
    if "\x00" in value:
        raise ManifestError(f"{kind} contains a NUL byte")
    if "/" in value or "\\" in value:
        raise ManifestError(f"{kind} {value!r} contains a path separator")
    if value in (".", "..") or os.path.isabs(value):
        raise ManifestError(f"{kind} {value!r} is not usable as a filename")
    return value


def load_manifest(path: str | os.PathLike, limit: int = 0,
                  audio_root: str | os.PathLike | None = None,
                  strict: bool = False,
                  shard: tuple[int, int] | None = None) -> list[dict]:
    """Read a manifest and attach a validated absolute ``_path`` to every row.

    ``id`` defaults to the audio file's basename. Rows whose audio cannot be
    resolved are skipped with a warning, or raise when ``strict``.

    ``shard=(i, n)`` keeps only the rows this worker owns. Selecting here rather than
    from the returned list matters twice over. It avoids resolving rows assigned
    to other workers. It is also more correct: shard
    membership is a pure function of the row, so a row that fails to resolve cannot shift
    every later row into a different worker.

    Ownership is by **line number** (``index % n == i``) unless a row carries
    ``parent_id``, in which case it is by a stable hash of that instead, so every segment
    of one recording lands on one worker. That is not cosmetic on long audio: segments
    are slices of a container that has to be decoded to read any of them. Grouping
    siblings lets the decoded-container cache work. crc32, not hash(): the builtin
    is salted per process, so two workers would
    disagree about who owns a row.
    """
    rows, skipped = [], 0
    for index, row in enumerate(read_jsonl(path)):
        if shard is not None:
            group = row.get("parent_id")
            key = zlib.crc32(str(group).encode()) if group else index
            if key % shard[1] != shard[0]:
                continue
        if not row.get("wav_path") and row.get("source_tar") and row.get("source_member"):
            # wav_path wins when both are present: a cut manifest keeps its provenance,
            # and a row that names a local copy must not silently read from the tar
            # a row that names a tar member has no file to resolve; the bytes are read
            # at annotation time (see continuo_expressive.tarsource)
            row.setdefault("id", str(row["source_member"]).rsplit("/", 1)[-1])
            rows.append(row)
            if limit and len(rows) >= limit:
                break
            continue
        if "wav_path" not in row:
            e = ManifestError("row has neither wav_path nor source_tar+source_member")
            if strict:
                raise e
            skipped += 1
            print(f"[warn] skip: {e}", file=sys.stderr)
            continue
        try:
            resolved = resolve_audio_path(row["wav_path"], audio_root)
        except ManifestError as e:
            if strict:
                raise
            skipped += 1
            print(f"[warn] skip: {e}", file=sys.stderr)
            continue
        row["_path"] = resolved
        row.setdefault("id", resolved.name)
        rows.append(row)
        if limit and len(rows) >= limit:
            break
    if skipped:
        print(f"[warn] {path}: skipped {skipped} row(s) with unusable wav_path",
              file=sys.stderr)
    return rows
